### ISSUE TITLE
Incomplete command requiredSelfPermissions

### ISSUE THREAD

**Issue by Murky-MoMo** [OmsinKrissada/J.A.R.V.I.S.-the-Discord-Bot#5]
**Describe the bug**
*A clear and concise description of what the bug is.*

Most of the commands have incompleted requiredSelfPermissions, by that i mean, commands such as _help_ that send embeds don't have **EMBED_LINKS** in the requiredSelfPermissions
and as said in the guide [source](https://discordjs.guide/popular-topics/permissions-extended.html#implicit-permissions) you'll need **VIEW_CHANNEL** to send a message, that should be added too

**Comment by OmsinKrissada** [comment]
Thank you for pointing that out :)

Never thought someone would find this repo haha

**Comment by Murky-MoMo** [comment]
also forgot to mention, that's the same issue with purge and other commands, it needs ADD_REACTIONS
aand as the link I sent says, it also needs **READ_MESSAGE_HISTORY**

**Comment by OmsinKrissada** [comment]
Thanks, I will check for `VIEW_CHANNEL` in CommandManager.
For `READ_MESSAGE_HISTORY` and  `ADD_REACTIONS` I will add a check in the array and also in `Helper.confirmClick()`.
`EMBED_LINKS` will be added to that array as usual.

Is this okay?

**Comment by Murky-MoMo** [comment]
yes thanks :)
